### ISSUE TITLE
Posts with Images Do Not Generate

### ISSUE THREAD

**Issue by trst** [masukomi/JekyllMail#5]
When JekyllMail runs and finds a post with no images attached it generates a markdown file; however, when a post with images attached is found, the images are saved accordingly, but the post is not generated.

Any thoughts?

**Comment by whiskeyzulu** [comment]
I've just started playing with this today and am experiencing the same behavior.  Has any resolution been found?

**Comment by masukomi** [comment]
Closing this issue as it should be addressed now.

Please reopen if you are still having problems.
